config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  root "pins#index"

  resources :pins do
  member do
    put "like", to: "pins#upvote"
    put "dislike", to: "pins#downvote"
   end
   end 

end

app/models/pin.rb
class Pin < ActiveRecord::Base
     belongs_to :user

     
     validates :description, presence: true
     validates :button, presence: true
     validates :testimonialtop, presence: true
     validates :testimonialbottom, presence: true
     validates :company, presence: true
     validates :meme, presence: true
     validates :profit, presence: true
     validates :question, presence: true
     validates :background, presence: true
     validates :market, presence: true

     acts_as_votable

     def score
       self.get_upvotes.size - self.get_downvotes.size
     end  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pins = Pin.all.order("created_at DESC")

  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  def upvote
      @pin = Pin.find(params[:id])
      @pin.upvote_by current_user
      redirect_to pins_path
    end

    def downvote
      @pin = Pin.find(params[:id])
      @pin.downvote_by current_user
      redirect_to pins_path
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this landing page" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :company, :button, :testimonialtop, :testimonialbottom, :meme, :market, :question, :profit, :background)
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Landingpage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
 <%= render 'layouts/header' %>



	<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
    <% end %>

   <%= yield %>


</body>
</html>

app/views/pages/_home.html.erb
<nav class="navbar  navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="navbar-brand">
      <%= link_to "Uber for Grocery. Fucking. Coupons.", root_path %></li>
    </div>  
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> Create a Better Landing Page
            <% end %>
          </li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <% else %>
          <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> Create a Better Landing Page
            <% end %>
          </li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div>
</nav>
   
<div class="clouds jumbotron">
	<div class="container">
    <% if user_signed_in? %>
    <div class="well well-sm centertext greentext">
      Sweet, you are on the early app release email list. Make your own landing pages while you wait and vote for other user landing pages.
      </div>     
    <% else %>
    <% end %> 
    </br>
 
  
  <h1>This app gonna be like</h1>
  <h1>Uber</h1>
  <h1><i>for</i></h1>
  <h1>Grocery. Fucking. Coupons.</h1>
  
  </br>
  </br>

      </br>
      <% if user_signed_in? %>
          <%= link_to "Think you can do better? Make your own damn App Landing Page", new_pin_path, class: "btn btn-primary btn-lg" %>
        </br>
     <% else %>
       <p>
         <%= link_to "YOLO", new_user_registration_path, class: "btn btn-success btn-lg" %>
       </p>
  <% end %> 
   </br>
   

   <div id="share-buttons">

<!-- Reddit -->
<a href="http://reddit.com/submit?url=http://www.thisappisbetterthanyours.com&title=" target="_blank"><img src="http://www.simplesharebuttons.com/images/somacro/reddit.png" alt="Reddit" /></a>    
 
<!-- Facebook -->
<a href="http://www.facebook.com/sharer.php?u=http://www.thisappisbetterthanyours.com" target="_blank"><img src="http://www.simplesharebuttons.com/images/somacro/facebook.png" alt="Facebook" /></a>
 
<!-- Twitter -->
<a href="http://twitter.com/share?url=http://www.thisappisbetterthanyours&text=Check out this swag new app idea!&hashtags=swag" target="_blank"><img src="http://www.simplesharebuttons.com/images/somacro/twitter.png" alt="Twitter" /></a>
 
</div>

</br>

  </div> 
</div>

<div class="testimonial">
	  <h3 class="centertext">Our User Loves Us:</h3>
	  <h4 class="centertext text-muted">"Your app saves me so much money grocery shopping!"</h5>
	  <img class="oag img-circle"></img>
	  <h4 class="centertext text-muted">"You won't let anyone else download it, will you?"
	</br>
</div>
</br>

      <!-- Three columns of text below the carousel -->
      <div class="row centertext blueback cloudtext">
      </br>
      <h3>Here's our Brilliant Business Plan:</h3>
    </br>
      <div class="container">
        <div class="col-lg-4">
          <img class="mountainPlaceholder roundedrec"></img>
          <h2>Step 1</h2>
          <p>That epic pic we found on the internet looks awesome doesn't it? How could our app not be successful? Epic pics courtesty of superfamous.com.</p>
          
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="questionPlaceholder roundedrec"></img>
          <h2>Step 2</h2>
          <p>????</p>
          
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="barsPlaceholder roundedrec"></img>
          <h2>Profit</h2>
          <p>It turns out we can save you boatloads of Zimbabwean dollars at the Grocery Store. Maybe you will spare us a suitcase of your loot? If not, ads. ads. ads.</p>
        </div><!-- /.col-lg-4 -->
      </div>
    </br>
      </div><!-- /.row -->

<div class="blueback">
</br>
</br>
<div img class="iphone"></img>
  <div class="text-box">
    <div class="text"> PUSH FOR  </div>
    <div class="text-2">GROCERY. FUCKING. COUPONS.</div>
  </div>
  </div>
</div>      
<audio loop class='audio' id='audio' loop>
  <source src='/assets/guile-theme.mp3' type='audio/mpeg'>
</audio>


<div class="bottomline">
  </br>
	<h4 class="centertext">The Uber for Grocery. Fucking. Coupons. App&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2014&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Coming Real Soon</h4>
  </br>	
</div>	

app/views/pages/home.html.erb
<h1>This app gonna be like</h1>
<h1>Uber</h1>
<h1><i>for</i></h1>
<h1>Grocery. Fucking. Coupons.</h1>
  
  </br>
  </br>

<% if user_signed_in? %>
          <h1>YEEEAAAAAAAAHHHHHHHHHHHHH!!!!!!!!!!!!!!!!!!!!!!!!</h1>
     <% else %>
       <p>
         <%= link_to "YOLO", new_user_registration_path, class: "btn btn-success btn-lg" %>
       </p>
  <% end %>  

app/views/pins/edit.html.erb
<nav class="navbar  navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="navbar-brand">
      <%= link_to "Uber for Grocery. Fucking. Coupons.", root_path %></li>
    </div>  
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> Create a Better Landing Page
            <% end %>
          </li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <% else %>
          <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> Create a Better Landing Page
            <% end %>
          </li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div>
</nav>
</br>

<div class="container">

<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

</div>

app/views/pins/index.html.erb
<%= render 'pages/home' %>
<div class="container">
</br>
<h2 class="centertext">Check out and invest in user created app landing pages</h2>
</br>
<div class="centering"><%= link_to "Make your own Landing Page in 60 seconds", new_pin_path, class: "btn btn-success btn-sm centering centertext" %></div>
</br>
 <div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <div class="panel-body centertext">
        <h4>
        <strong><%= link_to pin.description + ' for ' + pin.market, pin_path(pin) %></strong>
      </h4>

        <p> Investment $ Received: $<% if pin.score < 1 %><%= 0 %><% else %><%= pin.get_upvotes.size * 250000 %><% end %> </p>
        <p> # of Investors: <%= pin.get_upvotes.size %> | # of Hater VCs: <%= pin.get_downvotes.size %></p> 
        
        <p>Stage: <% if pin.get_upvotes.size < 2 %> <%= 'Friends & Family' %>
          <% elsif pin.get_upvotes.size < 8 %><%= 'Seed' %>
          <% elsif pin.get_upvotes.size < 31  %><%= 'Series A' %>
          <% elsif pin.get_upvotes.size < 59  %><%= 'Series B' %>
          <% elsif pin.get_upvotes.size < 99  %><%= 'Series C' %>
          <% else pin.get_upvotes.size >= 150 %><%= 'IPO' %><% end %>
         </p> 

         <p>Yearly Profit Run Rate:</p>
         <p> $<% if pin.get_upvotes.size < 2 %><%= (pin.get_upvotes.size - (pin.get_downvotes.size * 2)) * 115 %>
          <% elsif pin.get_upvotes.size < 8 %><%= (pin.get_upvotes.size - (pin.get_downvotes.size * 2)) * 1125 %>
          <% elsif pin.get_upvotes.size < 31 %><%= (pin.get_upvotes.size - (pin.get_downvotes.size * 2)) * 115000 %>
          <% elsif pin.get_upvotes.size < 59 %><%= (pin.get_upvotes.size - (pin.get_downvotes.size * 2)) * 715000 %>
          <% elsif pin.get_upvotes.size < 99 %><%= (pin.get_upvotes.size - (pin.get_downvotes.size * 2)) * 1515000 %>
          <% else pin.get_upvotes.size >= 99 %><%= (pin.get_upvotes.size - (pin.get_downvotes.size * 2)) * 10115000 %><% end %></p>


        <p>Founder: <%= pin.user.name if pin.user %></p>
        <h4><strong><%= link_to "Invest", like_pin_path(pin), method: :put %> |   
        <%= link_to "Reject", dislike_pin_path(pin), method: :put %></strong></h4>


        <% if pin.user == current_user %>
          <div class="actions">
            <%= link_to 'Edit', edit_pin_path(pin) %> |
             <%= link_to ' Delete', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        <% end %>
      </br>
<div id="share-buttons">

<!-- Reddit -->
<a href="http://reddit.com/submit?url=http://www.thisappisbetterthanyours.com&title=" target="_blank"><img src="http://www.simplesharebuttons.com/images/somacro/reddit.png" alt="Reddit" /></a>    
 
<!-- Facebook -->
<a href="http://www.facebook.com/sharer.php?u=http://www.thisappisbetterthanyours.com" target="_blank"><img src="http://www.simplesharebuttons.com/images/somacro/facebook.png" alt="Facebook" /></a>
 
<!-- Twitter -->
<a href="http://twitter.com/share?url=http://www.thisappisbetterthanyours&text=Simple Share Buttons&hashtags=swag" target="_blank"><img src="http://www.simplesharebuttons.com/images/somacro/twitter.png" alt="Twitter" /></a>
 
</div>


      </div>
    </div>
  <% end %>
 </div>
</br>
</div>

app/views/pins/new.html.erb
<nav class="navbar  navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="navbar-brand">
      <%= link_to "Uber for Grocery. Fucking. Coupons.", root_path %></li>
    </div>  
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> Create a Better Landing Page
            <% end %>
          </li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <% else %>
          <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> Create a Better Landing Page
            <% end %>
          </li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div>
</nav>

<div class="container">
  <h1 class="centertext">Make Your Own Landing Page</h1>

  <%= render 'form' %>

  <%= link_to 'Back', pins_path %>
</div>  

app/views/pins/show.html.erb
<nav class="navbar  navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="navbar-brand">
      <%= link_to  @pin.company, root_path %>
    </div>  
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> Create a Better Landing Page
            <% end %>
          </li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <% else %>
          <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> Create a Better Landing Page
            <% end %>
          </li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div>
</nav>


<div class="<%= @pin.background %> jumbotron">
	<div class="container">

  </br>
  </br>  
  
  <h1>This app gonna be like</h1>
  <h1><%= @pin.description %></h1>
  <h1><i>for</i></h1>
  <h1><%= @pin.market %></h1>
  
  </br>
  </br>


    
       <p>
         <%= link_to "YOLO", new_user_registration_path, class: "btn btn-success btn-lg" %>
       </p>
 
   </br>

<div id="share-buttons">

<!-- Reddit -->
<a href="http://reddit.com/submit?url=http://www.thisappisbetterthanyours.com&title=Simple Share Buttons" target="_blank"><img src="http://www.simplesharebuttons.com/images/somacro/reddit.png" alt="Reddit" /></a>    
 
<!-- Facebook -->
<a href="http://www.facebook.com/sharer.php?u=http://www.thisappisbetterthanyours.com" target="_blank"><img src="http://www.simplesharebuttons.com/images/somacro/facebook.png" alt="Facebook" /></a>
 
<!-- Twitter -->
<a href="http://twitter.com/share?url=http://www.thisappisbetterthanyours.com&text=Check out this swag new App&hashtags=simplesharebuttons" target="_blank"><img src="http://www.simplesharebuttons.com/images/somacro/twitter.png" alt="Twitter" /></a>
 
 
</div>

   </br>

   
  </div> 
</div>

<div class="testimonial">
	  <h3 class="centertext">Our User Loves Us:</h3>
	  <h4 class="centertext text-muted">"<%= @pin.testimonialtop %>"</h5>
	  <img class="<%= @pin.meme %> img-circle"></img>
	  <h4 class="centertext text-muted">"<%= @pin.testimonialbottom %>"
	</br>
</div>
</br>

 <!-- Three columns of text below the carousel -->
      <div class="row centertext blueback cloudtext">
      </br>
      <h3>Here's our Brilliant Business Plan:</h3>
    </br>
      <div class="container">
        <div class="col-lg-4">
          <img class="mountainPlaceholder roundedrec"></img>
          <h2>Step 1</h2>
          <p><%= @pin.question %></p>
          
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="questionPlaceholder roundedrec"></img>
          <h2>Step 2</h2>
          <p>????</p>
          
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="barsPlaceholder roundedrec"></img>
          <h2>Profit</h2>
          <p><%= @pin.profit %></p>
        </div><!-- /.col-lg-4 -->
      </div>
    </br>
      </div><!-- /.row -->

<div class="blueback">
</br>
</br>
<div img class="iphone"></img>
  <div class="text-box">
    <div class="text"> PUSH FOR  </div>
    <div class="text-2"><%= @pin.button %></div>
  </div>
  </div>
</div>      
<audio loop class='audio' id='audio' loop>
  <source src='/assets/guile-theme.mp3' type='audio/mpeg'>
</audio>

<div class="bottomline">
  </br>
  <div class="container">
	<h4 class="centertext"><%= @pin.company %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2014&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Founded by <%= @pin.user.name if @pin.user %></h4>
</br>
  <h4 class="centertext"> <%= link_to "Invest", like_pin_path(@pin), method: :put %> | 
  <%= link_to "Reject", dislike_pin_path(@pin), method: :put %> </h4>
  <h6 class="centertext"><strong>Startup Stats:</strong> Investment $ Received: $<% if @pin.score < 1 %><%= 0 %><% else %><%= @pin.get_upvotes.size * 250000 %><% end %> | # of Investors: <%= @pin.get_upvotes.size %> | # of Hater VCs: <%= @pin.get_downvotes.size %> | Startup Stage: <% if @pin.get_upvotes.size < 2 %> <%= 'Friends & Family' %><% elsif @pin.get_upvotes.size < 8 %><%= 'Seed' %><% elsif @pin.get_upvotes.size < 31  %><%= 'Series A' %><% elsif @pin.get_upvotes.size < 59  %><%= 'Series B' %><% elsif @pin.get_upvotes.size < 99  %><%= 'Series C' %><% else @pin.get_upvotes.size >= 150 %><%= 'IPO' %><% end %> | Yearly Profit Run Rate: $<% if @pin.get_upvotes.size < 2 %><%= (@pin.get_upvotes.size - (@pin.get_downvotes.size * 2)) * 115 %><% elsif @pin.get_upvotes.size < 8 %><%= (@pin.get_upvotes.size - (@pin.get_downvotes.size * 2)) * 1125 %><% elsif @pin.get_upvotes.size < 31 %><%= (@pin.get_upvotes.size - (@pin.get_downvotes.size * 2)) * 115000 %><% elsif @pin.get_upvotes.size < 59 %><%= (@pin.get_upvotes.size - (pin.get_downvotes.size * 2)) * 715000 %><% elsif @pin.get_upvotes.size < 99 %><%= (@pin.get_upvotes.size - (@pin.get_downvotes.size * 2)) * 1515000 %><% else @pin.get_upvotes.size >= 99 %><%= (@pin.get_upvotes.size - (@pin.get_downvotes.size * 2)) * 10115000 %><% end %></h6> 
</br>
    <h5 class="centertext"><%= link_to 'Back', root_path %> 
     <% if @pin.user == current_user %>
         <%= link_to '| Edit Your Landing Page', edit_pin_path(@pin) %>
        <% end %> 
      <%= link_to new_pin_path do %>
               | Make New Page
            <% end %>
          </br>
      </h5> 
    </br>
    </div>
  </br>	
</div>	